# Generated by Django 5.1.1 on 2024-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
